language: node_js
node_js:
    - 0.10
env:
    global:
        - secure: "k83UvX8Q6bKfPl5PJfii/BV10x7vnp45815OLlJ6DX1AxNukNF76f4ebuI62\nKQiwHOeG5YTZpoJ0jZMD66CgMSH7wA6ciWKjN9EdWjqmRj+cWM/Na0PF4Rme\njJVenAWAcwXDKHpXXa8St+AIWQafuZL3AlDfvNaMLeIKSLcxd4U="
        - secure: "Q+XsRRGML8LxHFBJRhtFPF32SnRrl6cNH2wl3i/tPk8CCVMuhAMJh/UNiulS\nVzohU3ONMJVnDSKiAArj3bOwkcFIcULU8hVMLoDia262Y8VOhjUEWryTE5la\nu0h09mgPyfixt0GVb3WVmB7R9uglQm4/+ewF8qUPY6qLjow4cV4="
script: grunt test
