language: node_js
node_js:
    - 0.10
env:
    global:
        - secure: "icYPF/lYpeiE4bUY3kpCIqJEYWtp7eA0WAG/f74vkTYrh+HEjYeu4Z/ZmoSu\nNbZAa8O0GzQFZuyuxTL/ulCjBcpO2NJYhYY/+aQ6NUGObsETN2Xo6z5J2/ul\nSsXPvh0/iWrkQGamur5WXK9sg0/Jd4rp0588mOkl3Xyr0lmVTvI="
        - secure: "XuoAUhfWHIGIreg16qRK0vX/ftcxetnQhuHUCR+eCrCDjqkGl1/0kImtlHEQ\nAluHsKoJky+UNfnvNyY2Y0ms68XV8P7MWSgfGq7jxiScRWERtCDDI7CXMw1N\nyxKSRGi004wW1Nq7P6zAsKNsqQ7bJXlTn8n303j5vxCUvVxwAHY="
script: grunt test
