env: 
  global: 
  - secure: bCpBrmyTR7cVuT3UpNXdlDuf3Q6Qkgo2tfnHcKprm/hbtYxycvRzA8Ve4uQVE/mLtwD8S1T+NCGmidua3DUjHQ2vTVWralXmnDG38c0z8IpBBqgm/+Wa+L4aRzng0XzjnFR3XPN/sfdhnud1y419JqaeUmjAxDxeqtRmnMJKYYA=
  - secure: CX3245pwuWZlZ0BjO7OTUekYcDNxGq0wvuzkzT+5H3OeBMRfT8S7CnqVXBwnbcStB09M+8vzeY/W0gvDskh68xA9p3H0XzuTdtm8+1+NnGbdOOdTwkf+luUXuTSrNPz2/IzB2Tin8A5Xqk4aGuj7s8inkUH8KsRY5KEKE/CYZbM=
language: node_js
node_js: 
- 0.1
script: grunt test
